<?php /* Smarty version Smarty-3.1.21, created on 2018-07-23 04:05:58
         compiled from "C:\xampp\htdocs\tikiwiki\tiki-18.1\templates\admin\include_rss.tpl" */ ?>
<?php /*%%SmartyHeaderCode:14948823815b553806a9cfe8-95660172%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '6bf2d4268b73dd5ae4d0d5b77c27872c513ec69e' => 
    array (
      0 => 'C:\\xampp\\htdocs\\tikiwiki\\tiki-18.1\\templates\\admin\\include_rss.tpl',
      1 => 1492545646,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '14948823815b553806a9cfe8-95660172',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.21',
  'unifunc' => 'content_5b553806b41103_54877251',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5b553806b41103_54877251')) {function content_5b553806b41103_54877251($_smarty_tpl) {?><?php if (!is_callable('smarty_block_remarksbox')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\block.remarksbox.php';
if (!is_callable('smarty_block_tr')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\block.tr.php';
if (!is_callable('smarty_function_ticket')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\function.ticket.php';
if (!is_callable('smarty_function_icon')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\function.icon.php';
if (!is_callable('smarty_block_tabset')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\block.tabset.php';
if (!is_callable('smarty_block_tab')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\block.tab.php';
if (!is_callable('smarty_function_preference')) include 'C:/xampp/htdocs/tikiwiki/tiki-18.1/lib/smarty_tiki\\function.preference.php';
?><?php $_smarty_tpl->smarty->_tag_stack[] = array('remarksbox', array('type'=>"tip",'title'=>"Tip")); $_block_repeat=true; echo smarty_block_remarksbox(array('type'=>"tip",'title'=>"Tip"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

	Use this page to configure the feeds generated by Tiki. To syndicate feeds from other sites, use <a class="alert-link" href="tiki-admin_rssmodules.php" title="<?php $_smarty_tpl->smarty->_tag_stack[] = array('tr', array()); $_block_repeat=true; echo smarty_block_tr(array(), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>
External Feeds">External Feeds</a>.<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tr(array(), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_remarksbox(array('type'=>"tip",'title'=>"Tip"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

<form class="form-horizontal" action="tiki-admin.php?page=rss" method="post">
	<?php echo smarty_function_ticket(array(),$_smarty_tpl);?>

	<div class="t_navbar margin-bottom-md clearfix">
		<a role="button" class="btn btn-link" href="tiki-admin_rssmodules.php" title="List">
			<?php echo smarty_function_icon(array('name'=>"list"),$_smarty_tpl);?>
 External Feeds
		</a>
		<?php echo $_smarty_tpl->getSubTemplate ('admin/include_apply_top.tpl', $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, null, array(), 0);?>

	</div>
	<?php $_smarty_tpl->smarty->_tag_stack[] = array('tabset', array('name'=>"admin_rss")); $_block_repeat=true; echo smarty_block_tabset(array('name'=>"admin_rss"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

		<?php $_smarty_tpl->smarty->_tag_stack[] = array('tab', array('name'=>"General Preferences")); $_block_repeat=true; echo smarty_block_tab(array('name'=>"General Preferences"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

			<br>
			<?php echo smarty_function_preference(array('name'=>'feed_default_version'),$_smarty_tpl);?>

			<div class="adminoptionboxchild feed_default_version_childcontainer 5">
				<?php echo smarty_function_preference(array('name'=>'feed_atom_author_name'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_atom_author_email'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_atom_author_url'),$_smarty_tpl);?>

			</div>
			<div class="adminoptionboxchild feed_default_version_childcontainer 2">
				<?php echo smarty_function_preference(array('name'=>'feed_rss_editor_email'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_rss_webmaster_email'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_img'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'feed_language'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'feed_cache_time'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'feed_basic_auth'),$_smarty_tpl);?>

		<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tab(array('name'=>"General Preferences"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

		<?php $_smarty_tpl->smarty->_tag_stack[] = array('tab', array('name'=>"Feeds")); $_block_repeat=true; echo smarty_block_tab(array('name'=>"Feeds"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

			<br>
			<?php echo smarty_function_preference(array('name'=>'feed_articles'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_articles_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-articles_rss.php" title=":Feed for articles">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_articles_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_articles_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_blogs'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_blogs_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-blogs_rss.php" title=":Feed for blogs">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_blogs_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blogs_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_blog'),$_smarty_tpl);?>

			<div class="adminoptionboxchild form-group clearfix" id="feed_blog_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-list_blogs.php" title=":Feed for individual blogs">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_blog_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_blog_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_image_galleries'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_image_galleries_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-image_galleries_rss.php" title=":Feed for image galleries">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_galleries_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_image_gallery'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_image_gallery_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-galleries.php" title=":Feed for individual image galleries">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_image_gallery_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_file_galleries'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_file_galleries_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-file_galleries_rss.php" title=":Feed for file galleries">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_galleries_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_file_gallery'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_file_gallery_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-list_file_gallery.php" title="Feed for individual file galleries">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_file_gallery_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_wiki'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_wiki_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-sm-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-wiki_rss.php" title=":Feed for wiki pages (with diff)">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View (with diff)
						</a>
						<a class="btn btn-default btn-sm tips timeout" href="tiki-wiki_rss_no_diff.php" title=":Feed for wiki pages (no diff)">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View (no diff)
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_wiki_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_wiki_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_forums'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_forums_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-forums_rss.php" title=":Feed for forums">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_forums_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forums_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_forum'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_forum_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-forums.php" title=":Feed for individual forums">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_forum_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_forum_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_tracker'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_tracker_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-list_trackers.php" title=":Feed for trackers">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_tracker_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_homepage'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_tracker_labels'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_calendar'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_calendar_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-calendars_rss.php" title=":Feed for calendars">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_calendar_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_calendar_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_directories'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_directories_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-directories_rss.php" title=":Feed for directories">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_directories_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_directories_homepage'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'feed_shoutbox'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="feed_shoutbox_childcontainer">
				<div class="form-group clearfix">
					<div class="col-md-8 col-md-push-4">
						<a class="btn btn-default btn-sm tips timeout" href="tiki-shoutbox_rss.php" title=":Feed for shoutbox">
							<?php echo smarty_function_icon(array('name'=>"rss"),$_smarty_tpl);?>
 View
						</a>
					</div>
				</div>
				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_title'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_desc'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_max'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_showAuthor'),$_smarty_tpl);?>

				<?php echo smarty_function_preference(array('name'=>'feed_shoutbox_homepage'),$_smarty_tpl);?>

			</div>
		<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tab(array('name'=>"Feeds"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

		<?php $_smarty_tpl->smarty->_tag_stack[] = array('tab', array('name'=>"Incoming Feeds")); $_block_repeat=true; echo smarty_block_tab(array('name'=>"Incoming Feeds"), null, $_smarty_tpl, $_block_repeat);while ($_block_repeat) { ob_start();?>

			<br>
			<?php echo smarty_function_preference(array('name'=>'page_content_fetch'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'page_content_fetch_readability'),$_smarty_tpl);?>

			<?php echo smarty_function_preference(array('name'=>'tracker_article_tracker'),$_smarty_tpl);?>

			<div class="adminoptionboxchild" id="tracker_article_tracker_container">
				<?php echo smarty_function_preference(array('name'=>'tracker_article_trackerId'),$_smarty_tpl);?>

			</div>
			<?php echo smarty_function_preference(array('name'=>'tracker_article_indexing'),$_smarty_tpl);?>

		<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tab(array('name'=>"Incoming Feeds"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

	<?php $_block_content = ob_get_clean(); $_block_repeat=false; echo smarty_block_tabset(array('name'=>"admin_rss"), $_block_content, $_smarty_tpl, $_block_repeat);  } array_pop($_smarty_tpl->smarty->_tag_stack);?>

	<?php echo $_smarty_tpl->getSubTemplate ('admin/include_apply_bottom.tpl', $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, null, array(), 0);?>

</form>
<?php }} ?>
